[2025-07-06 13:10:13,885] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:10:13] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:10:14,028] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:10:14] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:10:14,032] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:10:14] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:10:14,033] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:10:14] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:10:14,083] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:10:14] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:10:14,092] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:10:14] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:10:20,579] ERROR log_exception() L1414 Exception on /pessoa [POST] - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py L1414
Traceback (most recent call last):
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask_openapi3\scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py", line 113, in predict
    X_input = preprocessador.preparar_form(form)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\model\preprocessador.py", line 52, in preparar_form
    form.bike,
    ^^^^^^^^^
AttributeError: 'PessoaSchema' object has no attribute 'bike'
[2025-07-06 13:10:20,583] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:10:20] "[35m[1mPOST /pessoa HTTP/1.1[0m" 500 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:18,944] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:18,944] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:26,380] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:11:26] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:26,464] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:11:26] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:26,464] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:11:26] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:26,464] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:11:26] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:26,551] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:11:26] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:26,558] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:11:26] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:11:34,131] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:11:34] "POST /pessoa HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:21:40,108] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:21:40] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:21:44,562] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:21:44] "GET /pessoa?name=Maria HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:21:51,856] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:21:51] "GET /pessoas HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 13:21:56,963] ERROR log_exception() L1414 Exception on /pessoa [DELETE] - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py L1414
Traceback (most recent call last):
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\flask_openapi3\scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py", line 226, in delete_paciente
    pessoa_nome = unquote(query.nome)
                          ^^^^^^^^^^
AttributeError: 'PessoaBuscaSchema' object has no attribute 'nome'. Did you mean: 'name'?
[2025-07-06 13:21:56,968] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 13:21:56] "[35m[1mDELETE /pessoa?name=Maria HTTP/1.1[0m" 500 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
